---
swagger: "2.0"
info:
  description: "REST API for AIS\n"
  version: "1.0"
  title: "Attended Information System"
basePath: "/api"
schemes:
- "http"
paths:
  /pass:
    get:
      summary: "Lists all pass"
      description: "Lists all pass of users"
      operationId: "getPass"
      produces:
        - "application/json"
      parameters:
      - name: "usercode"
        in: "query"
        description: "Optional filtering by usercode"
        required: false
        type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pass"
        400:
          description: "Invalid status value"
  /pass/{passId}:
    get:
      summary: "Find pass by ID"
      description: "Returns a single pass"
      operationId: "getPassById"
      produces:
      - "application/json"
      parameters:
      - name: "passId"
        in: "path"
        description: "ID of pass to return"
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Pass"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pass not found"
  /pass/onsite:
    get:
      summary: "Find users onsite"
      description: "Returns a list on users onsite"
      operationId: "getUsersOnsite"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pass"
        400:
          description: "Invalid status value"
definitions:
  Pass:
    type: "object"
    properties:
      id:
        type: "integer"
      category:
        type: "string"
      chip:
        type: "string"
      date:
        type: "string"
        format: "date-time"
      person:
        $ref: '#/definitions/UserInfo'
    example:
      id: 221509
      category: "7"
      chip: "00000B207E8E"
      date: "2017-07-21T17:32:28Z"
  UserInfo:
    type: "object"
    properties:
      id:
        type: "integer"
      code:
        type: "integer"
      name:
        type: "string"
      department:
        type: "string"
    example:
      id: 282
      code: 166
      name: "Petr D."
      department: "02"